function Quiz({ quiz_name1, tags1, activity_points1, duration1, max_no_of_Attempts1, level_override1, slug1, description1, meta_keywords1, meta_description1, icon1, instructions1, category1, level1, pass_percentage1, is_available_pre_signup1, is_available_via_slug1, is_available_dashboard1, is_timer_enabled1, is_shuffle_questions1, is_shuffle_answers1, is_display_score1, is_allow_attempt_review1, is_show_whether_correct1, is_show_correct_answers_passed1, is_show_correct_answers_failed1, is_show_answer_explanations1, is_enable_save_resume1, quizQuesObj1 }: {
    quiz_name1;
    tags1;
    activity_points1;
    duration1;
    max_no_of_Attempts1;
    level_override1;
    slug1;
    description1;
    meta_keywords1;
    meta_description1;
    icon1;
    instructions1;
    category1;
    level1;
    pass_percentage1;
    is_available_pre_signup1;
    is_available_via_slug1;
    is_available_dashboard1;
    is_timer_enabled1;
    is_shuffle_questions1;
    is_shuffle_answers1;
    is_display_score1;
    is_allow_attempt_review1;
    is_show_whether_correct1;
    is_show_correct_answers_passed1;
    is_show_correct_answers_failed1;
    is_show_answer_explanations1;
    is_enable_save_resume1;
    quizQuesObj1;
}) {
    this.quiz_name = quiz_name1;
    this.tags = tags1;
    this.activity_points = activity_points1;
    this.duration = duration1;
    this.max_no_of_attempts = max_no_of_Attempts1;
    this.level_override = level_override1;
    this.slug = slug1;
    this.description = description1;
    this.meta_keywords = meta_keywords1;
    this.meta_description = meta_description1;
    this.icon = icon1;
    this.instructions = instructions1;
    this.category = category1;
    this.level = level1;
    this.pass_percentage = pass_percentage1;
    this.is_available_pre_signup = is_available_pre_signup1;
    this.is_available_via_slug = is_available_via_slug1;
    this.is_available_dashboard = is_available_dashboard1;
    this.is_timer_enabled = is_timer_enabled1;
    this.is_shuffle_questions = is_shuffle_questions1;
    this.is_shuffle_answers = is_shuffle_answers1;
    this.is_display_score = is_display_score1;
    this.is_allow_attempt_review = is_allow_attempt_review1;
    this.is_show_whether_correct = is_show_whether_correct1;
    this.is_show_correct_answers_passed = is_show_correct_answers_passed1;
    this.is_show_correct_answers_failed = is_show_correct_answers_failed1;
    this.is_show_answer_explanations = is_show_answer_explanations1;
    this.is_enable_save_resume = is_enable_save_resume1;
    this.quizQuestionObj = quizQuesObj1;
}
